server:
  port: 2000
spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cv?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6001/eureka/
zuul:
#  routes:
#    authentication-client: /author-client/**
#
#    authentication-cneter: /author-center/**

  ignored-services:
    authentication-client

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

