spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: true
      max-connections: 1
      idle-timeout: 3000
    user: admin
    password: admin
server:
  port: 6000